namespace RotMGCore.Structures.Game {
    public class StatDataUtils {
        public static bool IsUTF(StatDataType statData) {
            switch (statData) {
                case StatDataType.Name:
                case StatDataType.GuildName:
                case StatDataType.PetName:
                case StatDataType.AccountId:
                case StatDataType.OwnerAccountId:
                    return true;
                default:
                    return false;
            }
        }
    }

    public enum StatDataType {
        MaximumHP = 0,
        HP = 1,
        Size = 2,
        MaximumMP = 3,
        MP = 4,
        ExperienceGoal = 5,
        Experience = 6,
        Level = 7,
        Inventory0 = 8,
        Inventory1 = 9,
        Inventory2 = 10,
        Inventory3 = 11,
        Inventory4 = 12,
        Inventory5 = 13,
        Inventory6 = 14,
        Inventory7 = 15,
        Inventory8 = 16,
        Inventory9 = 17,
        Inventory10 = 18,
        Inventory11 = 19,
        Attack = 20,
        Defense = 21,
        Speed = 22,
        Vitality = 26,
        Wisdom = 27,
        Dexterity = 28,
        Effects = 29,
        Stars = 30,
        Name = 31,
        Texture1 = 32,
        Texture2 = 33,
        MerchantMerchandiseType = 34,
        Credits = 35,
        SellablePrice = 36,
        PortalUsable = 37,
        AccountId = 38,
        CurrentFame = 39,
        SellablePriceCurrency = 40,
        ObjectConnection = 41,
        MerchantRemainingCount = 42,
        MerchantRemainingMinute = 43,
        MerchantDiscount = 44,
        SellableRankRequirement = 45,
        HPBoost = 46,
        MPBoost = 47,
        AttackBonus = 48,
        DefenseBonus = 49,
        SpeedBonus = 50,
        VitalityBonus = 51,
        WisdomBonus = 52,
        DexterityBonus = 53,
        OwnerAccountId = 54,
        NameChangerStar = 55,
        NameChosen = 56,
        Fame = 57,
        FameGoal = 58,
        Glowing = 59,
        SinkOffset = 60,
        AltTextureIndex = 61,
        GuildName = 62,
        GuildRank = 63,
        OxygenBar = 64,
        XpBoosterActive = 65,
        XpBoosterTime = 66,
        LootDropBoostTimer = 67,
        LootTierBoostTimer = 68,
        HealStackCount = 69,
        MagicStackCount = 70,
        Backpack0 = 71,
        Backpack1 = 72,
        Backpack2 = 73,
        Backpack3 = 74,
        Backpack4 = 75,
        Backpack5 = 76,
        Backpack6 = 77,
        Backpack7 = 78,
        Has_Backpack = 79,
        Skin = 80,
        PetId = 81,
        PetName = 82,
        PetType = 83,
        PetRarity = 84,
        PetMaximumLevel = 85,
        PetNothing = 86,
        PetPoints0 = 87,
        PetPoints1 = 88,
        PetPoints2 = 89,
        PetLevel0 = 90,
        PetLevel1 = 91,
        PetLevel2 = 92,
        PetAbilityType0 = 93,
        PetAbilityType1 = 94,
        PetAbilityType2 = 95,
        Effects2 = 96,
        Tokens = 97
    }
}